name = "StrLiterals"
desc = "Adds Swift-style string literal interpolation, extensible framework"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Strings", "Literals"]
license = "MIT"
uuid = "627f7b36-cfa1-4420-8f93-de9d4fe56cdc"
repo-rev = ""
repo-url = "https://github.com/JuliaString/StrLiterals.jl.git"
version = "0.1.0"
