name = "StrLiterals"
uuid = "68059f60-971f-57ff-a2d0-18e7de9ccc84"
keywords = ["Strings", "Literals"]
license = "MIT"
desc = "Adds Swift-style string literal interpolation, extensible framework"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
version = "0.1.6"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
